### ISSUE TITLE
Ubaryd errors out when airline is not installed

### ISSUE THREAD

**Issue by mrshu** [Donearm/Ubaryd#2]
Hi @Donearm,

Thanks a ton for putting together this nice vim theme!

I just wanted to let you know that most probably in 08faecdf1a626294c9dc69fea1b4982c3b02ca74 you introduced a call to `airline#themes#get_highlight` which errors out when `airline` is not installed -- the full error is 
```
line  323:
E117: Unknown function: airline#themes#get_highlight
E15: Invalid expression: airline#themes#get_highlight('StatusLine')
```

I am not sure if there is something that can be done with this -- most of the `vim-airline` themes deal with it [in the same way](https://github.com/vim-airline/vim-airline-themes/search?q=%22airline%23themes%23get_highlight%22&unscoped_q=%22airline%23themes%23get_highlight%22) and so my solution was simple: install `vim-airline` :)

I still think that it would be worth trying to make Ubaryd function smoothly even on Vim instances that do not use `vim-airline`.

Thanks again!

**Comment by Donearm** [comment]
Hey @mrshu,

thanks for pointing the error out. I didn't test it thoroughly as I should have, sorry.  I've made a fix in testing, a719c968ccfca3ca2ffb74edc3bd2bd17931dec4, which works for me. If it works also for you, I'll merge into master and close the issue :)

**Comment by mrshu** [comment]
Thanks @Donearm, I've tested your solution and it does work for me too.

Thanks a ton for your fast response!

**Comment by Donearm** [comment]
Cool, thanks a lot!
