### ISSUE TITLE
Strange colors (specifically in the Python context)

### ISSUE THREAD

**Issue by mrshu** [Donearm/Ubaryd#3]
Hi @Donearm,

I am sorry for bothering you once again, but I ran into an issue with `Ubaryd` that I was not able to debug properly and hope that you may have some insight that could be helpful.

I've changed my `.vimrc` in various ways today and one of those seems to have changed the way Python's `import` statements are colored. In the picture below you can see the previous version on the left and the new version on the right. What is notable is that the color of the `import` statement on the right is different from the color in the sample image that is in the README of `Ubaryd` repository (further below).

![screenshot from 2018-10-27 14-59-12](https://user-images.githubusercontent.com/461491/47604638-b5ce9200-d9fc-11e8-9b5c-3bca7e19d823.png)

![](https://camo.githubusercontent.com/7ac30c4603ef4f154fb7aa7c4af4c722740e7f76/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3132303833332f3739333938342f37383236643463342d656335622d313165322d383666322d6534346636306361346238322e706e67)

What you happen to know what may have caused an issue like this?

Thanks again!

**Comment by Donearm** [comment]
Screenshots in the README are not up to date. I was planning to upload new ones this weekend.

Your screenshot on the right looks then updated as it should with the latest version of Ubaryd but for the import statements (from, import) that you have `algae` while they are now `nut`. That's weird and I'm trying to reproduce it. What version of vim are you using? Did you try running `:set filetype=python` after opening the file, just to be 100% sure it is loading the correct syntax highlighting?

**Comment by mrshu** [comment]
@Donearm Thanks for your reply!

I run Vim 8.1 and sadly, I can see the same colors even after explicitly running `:set filetype=python`.

My current theory is that the way syntax highlighting is done must have changed. Would you happen to know what would be the best way of confirming that? I checked the Python syntax files but it does not seem they have changed.

**Comment by Donearm** [comment]
I did check that and it hasn't indeed changed. Nor I did change the `pythonInclude` there recently, it was the dark red in you left screenshot and it is now `nut`. 

Did the change happened after 08faecdf1a626294c9dc69fea1b4982c3b02ca74 or was older?

**Comment by mrshu** [comment]
Sadly, even if I get on 949593ca4b65688dda1a0031047a069be98c416d I still see the colors in the first picture I mentioned. It therefore looks like a local issue and not a change within `Ubaryd`.

If you had any clues as to what could have happened, I would very much appreciate it.

Thanks again!

**Comment by Donearm** [comment]
Uhm, looks like it was always taking the wrong colour. Tried changing the `pythonInclude` colour, the rgb code, to anything else? Does it show?
