### ISSUE TITLE
Background color not updated

### ISSUE THREAD

**Issue by Tekki** [Donearm/Ubaryd#5]
Under some conditions the background color is not updated:
```
$ vim some.yml
:color morning
:q
$ vim some.yml
:color ubaryd
```
Now it looks like this:
![ubaryd-background](https://user-images.githubusercontent.com/466122/48532933-b8f1cb00-e8a2-11e8-8e44-067af3dae578.png)

Sometimes this even happens when switching in vim from a bright theme to Ubaryd. But it doesn't happen if I switch to darkblue.

**Comment by Donearm** [comment]
uhm, darkblue has a dark background while morning has a "light" one. I'm testing but I can't reproduce it. Vim version and terminal?

**Comment by Tekki** [comment]
The screenshot is from Vim 8.1.477 on Debian Stretch on WSL. I'm going to test on other installations, wait for more feedback.
With darkblue I meant when I switch from morning to darkblue, all the background is dark, when I switch from morning to ubaryd it is not.

**Comment by Tekki** [comment]
Tested on a pure Debian installation with Vim 8.1.527 (works fine) and again with 8.1.527 on WSL. Seems this is an issue with bash in WSL, it doesn't reset the colors when Vim is closed. It can even happen that it switches to black on black.
Closing this issue for now. I'm going to compensate your lost time with a pr for Laederon.
